shared:
    image: node:8
    environment:
        ARTIFACTS_DIR: usertestpath
        TESTA: myenv\nh'el"lo
        TESTB: ${TESTA}world
        BLAH: $ARTIFACTS_DIR/blah
        SECRET: ${MYSECRET}issafe
        TESTDEPLOY: $APP.yaml

jobs:
    firstjob:
        requires: [~sd@989:job1, ~sd@989:job2, ~sd@989:job2]
        steps:
            - external: echo hello
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - teardownecho: env
            - export: export -p
            - deploy: APP=blah && echo $TESTDEPLOY
        secrets:
            - MYSECRET
        freezeWindows: ['* 20-23 ? * *']
    second:
        requires: [main]
        steps:
            - teardownecho: env
            - export: export -p
