shared:
    image: node:8

jobs:
    main:
        environment:
            GIT_SHALLOW_CLONE_DEPTH: 15
        requires:
            - ~pr
            - ~commit
        steps:
            - echo: env
            - depth: git log --oneline
            - get1: meta get meta.build.pipelineId
            - metacat: cat /sd/meta/meta.json
            - set-meta: |
                meta set trigger '{bar: { baz: {zoo: 1 }}}'
            - get-meta: meta get trigger.bar
            - set-meta2: |
                meta set trigger2 {bar: { baz: {zoo: 1 }}}
            - get-meta2: meta get trigger2.bar
            - cat: cat /sd/meta/meta.json
    job2:
        requires:
            - main
        steps:
            - echo: env
    job3:
        requires:
            - main
            - job2
        steps:
            - echo: env
