shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        environment:
            TESTA: 1
            TESTB: ${TESTA}2
        steps:
            - echo: env
