shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        environment:
            TESTA: myenv\nh'el"lo
            TESTB: ${TESTA}2
            BLAH: $ARTIFACTS_DIR/blah
        steps:
            - echo: env
            - export: export -p
            - setenv: export SD_PIPELINE_ID=1 && echo $SD_PIPELINE_ID
            - teardown-echo1: echo "$TESTA"
            - teardown-echo: echo $TESTB
