shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        environment:
            ARTIFACTS_DIR: usertestpath
            TESTA: myenv\nh'el"lo
            TESTB: ${TESTA}world
            BLAH: $ARTIFACTS_DIR/blah
            SECRET: ${MYSECRET}issafe
        steps:
            - teardownecho: env
            - export: export -p
        secrets:
            - MYSECRET
    second:
        requires: [main]
        steps:
            - teardownecho: env
            - export: export -p
