shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        environment:
            TESTA: "myenv\nhello"
            TESTB: "${TESTA}2"
        steps:
            - echo: env
            - teardown-echo: echo $TESTB
