shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - install: npm install
            - install-cli: - wget -q -O - https://github.com/screwdriver-cd/store-cli/releases/latest | egrep -o '/screwdriver-cd/store-cli/releases/download/v[0-9.]*/store-cli_linux_amd64' | wget --base=http://github.com/ -i - -O store-cli && chmod +x store-cli
            - cli-set: ./store-cli set mycache ./node_modules --type=cache --scope=events
            - echo: echo done
            
    no-cache:
        requires: [main]
        steps:
            - install-ci: npm install
            - echo: echo done
    
    with-cache:
        requires: [main]
        steps:
            - install-cli: - wget -q -O - https://github.com/screwdriver-cd/store-cli/releases/latest | egrep -o '/screwdriver-cd/store-cli/releases/download/v[0-9.]*/store-cli_linux_amd64' | wget --base=http://github.com/ -i - -O store-cli && chmod +x store-cli
            - cli-get: ./store-cli get mycache --type=cache --scope=events
            - install-ci: npm install
            - echo: echo done
            - sleep: sleep 1000
