shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - echo: env
            - set1: meta set pipelineId $SD_PIPELINE_ID
            - get1: meta get pipelineId
            - set-meta: |
                meta set trigger '{bar: { baz: {zoo: 1 }}}'
            - get-meta: meta get trigger.bar
            - set-meta2: |
                meta set trigger2 {bar: { baz: {zoo: 1 }}}
            - get-meta2: meta get trigger2.bar
            - rm: rm /sd/meta/meta.json
            - cat: cat /sd/meta/meta.json
