shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - install: npm install
            - echo: echo done
            
    no-cache:
        requires: [main]
        steps:
            - install-ci: npm install
            - echo: echo done
