shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        environment:
            TESTA: 1
            TESTB: ${TESTA}2
            USER_SHELL_BIN: bash
        steps:
            - echo: env
            - ls: ls -la
            - test: source testexport
            - echo2: env
