shared:
    image: node:8

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - install: npm install
            - pwd: pwd
            - ls: ls
            - store: cd .. && store-cli set ./node_modules/ --type=cache --scope=event
            - ls2: ls -la
            - echo: echo done
            
    cache:
        requires: [main]
        steps:
            - store: store-cli get ./node_modules --type=cache --scope=event
            - echo: echo done
